# Generated by Django 4.2.5 on 2024-09-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_channels", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockupdate",
            name="description",
        ),
        migrations.AddField(
            model_name="stockupdate",
            name="channel_product_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="stockupdate",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="channel",
            name="api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="api_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderupdate",
            name="message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stockupdate",
            name="err_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="channel",
            unique_together={("store", "types", "name")},
        ),
    ]
