# Generated by Django 4.2.5 on 2024-09-07 06:22

from django.db import migrations, models


def seed_data_commerce(apps, schema_editor):
    StoreModel = apps.get_model("app_channels", "Store")
    ChannelModel = apps.get_model("app_channels", "Channel")
    StockUpdateModel = apps.get_model("app_channels", "StockUpdate")
    OrderUpdateModel = apps.get_model("app_channels", "OrderUpdate")

    store, _ = StoreModel.objects.get_or_create(slug="test_store", defaults={"name": "test store", "api_secret": "test_store_secret"})

    channel, _ = ChannelModel.objects.get_or_create(slug="marketplace-shopee-dotuku", store=store, defaults={
        "name": "shopee", "types": "marketplace", "account_id": "123", "account_name": "dotuku",
        "api_key": "dotuku_key", "api_secret": "dotuku_secret"
    })
    
    StockUpdateModel.objects.get_or_create(product_id="0a28264c-2b2b-419c-903b-354e6737539a", channel=channel, defaults={
        "name": "test product 1", "channel_product_id": "channel_product_1", "sync_status": "pending", "stock": 50
    })
    StockUpdateModel.objects.get_or_create(product_id="09e5d4b9-558c-46aa-8179-496b9ae747da", channel=channel, defaults={
        "name": "test product 2", "channel_product_id": "channel_product_2", "sync_status": "pending", "stock": 40
    })
    StockUpdateModel.objects.get_or_create(product_id="a6accf0b-e4df-41f7-8860-0af0b68ca032", channel=channel, defaults={
        "name": "test product 3", "channel_product_id": "channel_product_3", "sync_status": "pending", "stock": 30
    })

    OrderUpdateModel.objects.get_or_create(order_id="test_order_dummy", defaults={
        "channel": channel, "status": "pending"
    })


def unseed_data_commerce(apps, schema_editor):
    StoreModel = apps.get_model("app_channels", "Store")
    ChannelModel = apps.get_model("app_channels", "Channel")
    StockUpdateModel = apps.get_model("app_channels", "StockUpdate")
    OrderUpdateModel = apps.get_model("app_channels", "OrderUpdate")
    
    OrderUpdateModel.objects.filter(order_id="test_order_dummy").delete()
    StockUpdateModel.objects.filter(channel__slug="test_marketplace_dotuku").delete()
    ChannelModel.objects.filter(store__slug="test_store").delete()
    StoreModel.objects.filter(slug="test_store").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("app_channels", "0002_update_table_attr"),
    ]

    operations = [
        migrations.RunPython(seed_data_commerce, unseed_data_commerce),
    ]
